= Hibernate Search 7.2.0.Alpha2 is out
Marko Bekhta
:awestruct-tags: [ "Hibernate Search", "Lucene", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
:hsearch-doc-url-prefix: https://docs.jboss.org/hibernate/search/7.2/reference/en-US/html_single/
:hsearch-getting-started-orm-url-prefix: https://docs.jboss.org/hibernate/search/7.2/getting-started/orm/en-US/html_single/
:hsearch-getting-started-standalone-url-prefix: https://docs.jboss.org/hibernate/search/7.2/getting-started/standalone/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse
:hsearch-version-family: 7.2
:hsearch-jira-project-id: 10061
:hsearch-jira-version-id: 32308
---

We just published Hibernate Search 7.2.0.Alpha2,
the second alpha release of the next minor version of Hibernate Search.

Compared to the previous alpha, this version contains the license change,
predicate improvements and more.

It also upgrades Lucene and Hibernate ORM dependencies and includes compatibility with the latest Elasticsearch 8.14.

== Switch project license to Apache License 2.0

We are pleased to announce that Hibernate Search 7.2.0.Alpha2 is licensed under Apache License 2.0,
which will be the license for all releases of Hibernate Search in the 7.2 series and later.
This change is a part of a broader initiative link:/2023/11/18/license/[to re-license Hibernate projects with the Apache License 2.0].

== What's new

[NOTE]
====
Hibernate Search 7.2 is still in its early stages of development:
some features are still incomplete or may change in a backwards-incompatible way.
====

=== Dependency upgrades

[[orm-version]]
Hibernate ORM (link:{hsearch-jira-url-prefix}/HSEARCH-5154[HSEARCH-5154])::
Hibernate Search now depends on Hibernate ORM 6.5.2.Final.
[[lucene-version]]
Lucene (link:{hsearch-jira-url-prefix}/HSEARCH-5166[HSEARCH-5166])::
The Lucene backend now uses Lucene 9.11.0.
[[elasticsearch-version]]
Elasticsearch (link:{hsearch-jira-url-prefix}/HSEARCH-5164[HSEARCH-5164])::
The Elasticsearch backend works with Elasticsearch 8.14, as well as other versions that were already compatible.
[[others-version]]
Others::
* link:{hsearch-jira-url-prefix}/HSEARCH-5165[HSEARCH-5165]: Upgrade to Elasticsearch **client** 8.14.0
* link:{hsearch-jira-url-prefix}/HSEARCH-5100[HSEARCH-5153]: Upgrade to GSON 2.11.0

[[range-within-withinany]]
=== `within`/`withinAny` for the range predicate

The link:{hsearch-doc-url-prefix}#search-dsl-predicate-range[`range`] predicate can now accept multiple ranges,
matching the document when the value is within at least one of the provided ranges.

[source, Java, indent=0, subs="+attributes"]
----
List<Book> hits = searchSession.search( Book.class )
        .where( f -> f.range().field( "pageCount" )
                .withinAny(
                        Range.between( 200, 250 ),
                        Range.between( 500, 800 )
                ) )
        .fetchHits( 20 );
----

[[other-changes]]
=== Other improvements and bug fixes

* link:{hsearch-jira-url-prefix}/HSEARCH-5161[HSEARCH-5161]:
Prevent mass indexer from dropping the schema on start when requested but multitenancy is configured.
* link:{hsearch-jira-url-prefix}/HSEARCH-5162[HSEARCH-5162]:
Ensure that Hibernate Search works correctly when Hibernate ORM's JPA compliance is enabled (`hibernate.jpa.compliance.query=true`).
* link:{hsearch-jira-url-prefix}/HSEARCH-5107[HSEARCH-5107]/link:{hsearch-jira-url-prefix}/HSEARCH-5108[HSEARCH-5108]:
Close Lucene index readers sooner.

And more.
Please see the link:https://hibernate.atlassian.net/issues/?jql=project={hsearch-jira-project-id}+AND+fixVersion={hsearch-jira-version-id}[release notes]
for a complete list of changes since the previous releases.

== How to get this release

All details are available and up to date on the
link:https://hibernate.org/search/releases/{hsearch-version-family}/#get-it[dedicated page on hibernate.org].

== Getting started, migrating

For new applications,
refer to the getting started guide:

* link:{hsearch-getting-started-orm-url-prefix}[here for the Hibernate ORM integration]
* link:{hsearch-getting-started-standalone-url-prefix}[here for the Standalone POJO Mapper]

For existing applications, Hibernate Search {hsearch-version-family} is a drop-in replacement for 7.1,
assuming you also upgrade the dependencies.
Information about deprecated configuration and API
is included in the https://docs.jboss.org/hibernate/search/{hsearch-version-family}/migration/html_single/[migration guide].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
